name: GDLauncher CI

on:
  push:
    branches:
      - master
      - releases
      - native-refactor
  pull_request:
    branches:
      - master
      - releases
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Install node-gyp
        if: matrix.os == 'windows-latest'
        run: |
         cd $(where node)
         cd node_modules\npm\node_modules\@npmcli\run-script
         npm install node-gyp@latest
