name: GDLauncher CI

on:
  push:
    branches:
      - master
      - releases
      - native-refactor
  pull_request:
    branches:
      - master
      - releases
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Install node-gyp
        if: matrix.os == 'windows-latest'
        run: |
         cd "C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script"
         npm install node-gyp@latest
